language: go

go:
  - '1.12'

services:
  - docker

env:
  - GO111MODULE=on

install:
  - go get -u golang.org/x/lint/golint
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
  - chmod +x get_helm.sh
  - ./get_helm.sh

before_script:
  - hack/verify-gofmt.sh
  - hack/verify-govet.sh
  - hack/verify-golint.sh
  - go mod verify
  - helm lint helm/botkube

script:
  - make test
  - make
  - make container-image
  - make publish

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push killcity/botkube:$TRAVIS_BRANCH
